### ISSUE TITLE
Issue of unsupported type with sample code of simple navigation

### ISSUE THREAD

**Issue by HuazeTang** [ai4ce/DeepParticleRobot#1]
I am trying to test the envrionment via the given sample code of simple navigation in the readme. However, I have an issue of unsupported type error. Here are the outputs:

```
Traceback (most recent call last):
  File "test_code.py", line 26, in <module>
    obs = env.reset()
  File "/home/huaze/anaconda3/envs/particleRobot/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 16, in reset
    return self.env.reset(**kwargs)
  File "/home/huaze/DeepParticleRobot/gym_dpr/envs/dpr_single_env.py", line 316, in reset
    self.world.removeAll()
  File "/home/huaze/DeepParticleRobot/gym_dpr/envs/DPR_World.py", line 280, in removeAll
    self.space.remove(self.space.bodies)
  File "/home/huaze/anaconda3/envs/particleRobot/lib/python3.7/site-packages/pymunk/space.py", line 431, in remove
    raise Exception(f"Unsupported type  {type(o)} of {o}.")
Exception: Unsupported type  <class 'list'> of [].
```

I am on ubuntu 20.04 and here are the package version I am using:

```
matplotlib                 3.5.1
numpy                      1.21.5
pygame                     2.1.2
pymunk                     6.2.1
gym                        0.21.0
```

**Comment by simbaforrest** [comment]
Thanks for reporting this. @jshen04 can you take a look (and update the repo accordingly)?

**Comment by jshen04** [comment]
@anetnna It appears that our code was using an older version of pymunk, but hopefully it is resolved now. Please let me know if you have any other issues.

**Comment by HuazeTang** [comment]
@jshen04 Many thanks! The gui is displaying now. I have switched all packages into the version in requirements.txt. Namely,

```
matplotlib                 3.4.2
numpy                      1.20.3
pygame                     2.0.1
pymunk                     5.5.0
gym                        0.21.0
```

However, the display seems to have some problems. I could barely see anything in the gui. Is it normal?
![gui_DPR](https://user-images.githubusercontent.com/108546362/180370867-c73c3c4d-5bcb-4216-a94c-5b1cd16bb85f.png)

**Comment by jshen04** [comment]
@anetnna Most likely the particle robots are out of the dimensions of the visualizer. Note the visualizer as it is only displays the first quadrant (default width=600, height=500). 

When initializing the environment, with the default arguments, the starting location of the particle robots is randomly generated. You are able to fix the starting position by changing the arguments.
>fixedStart=False, fixedGoal=True,
fixedStartCoords=None, fixedGoalCoords=(0, 0),
polarStartCoords=True, polarGoalCoords=False,
transformRectStart=(0, 0), transformRectGoal=(0, 0),
xLower=-1000, xUpper=1000, yLower=-1000, yUpper=1000,
radiusLower=450, radiusUpper=550, angleLower=0, angleUpper=2 * math.pi,

Set `fixedStart` to `True`, and set `polarStartCoords` to `True` if you wish to use polar coordinates and `False` if you wish to use cartesian coordinates. Then set `fixedStartCoords` to your desired starting coordinates (in the first quadrant). The particle robots should be visible under this setup. 

During training we just wish to randomly initialize the starting position.

**Comment by HuazeTang** [comment]
@jshen04 I followed your instruction and saw the output! Thanks a lot!
![running_gui](https://user-images.githubusercontent.com/108546362/180596624-1c6136a2-c85f-4d55-81e2-a62fdf1fd4fd.png)
